# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.31

    working_directory: ~/repo

   steps:
      - checkout
      - run: echo "A first hello"
